### ISSUE TITLE
Create basic test for server integration

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3Exporters#11]
Please create  RSAFrameExporterTest,

- testExportingBox
- testExportingEllipse
- testExportingLine

you can use this base in your tests

```Smalltalk
stream := WriteStream on: String new.
stream nextPutAll: 'foo'.
self assert: stream contents equals: 'foo'.
```

**Comment by ThisIsAntonio** [comment]
Milton, I create all TestCases necessary. Add image, and all passed.

![image](https://user-images.githubusercontent.com/51344799/97055596-80160280-155d-11eb-830f-a97ffcd9a66f.png)

**Comment by akevalion** [comment]
Server integration is working well with the last pull request https://github.com/ObjectProfile/Roassal3Exporters/pull/14
