### ISSUE TITLE
The floor shouldn't hide elements of the visualization

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3Exporters#12]
When a visualization has elements close enough to position y=0, the floor hides them.

I propose this solution:
When the HTML is writtten, calculate the initial y position of the floor in with the min y position of all elements.

**Comment by ThisIsAntonio** [comment]
Update the code and now we can see the canvas up the floor.

![image](https://user-images.githubusercontent.com/51344799/98581625-8667e680-22a0-11eb-8d53-b7af9b1a7e7b.png)

![image](https://user-images.githubusercontent.com/51344799/98581649-8f58b800-22a0-11eb-9aad-b77a2e3f9c6e.png)

```smalltalk
visitCanvas: aRSCanvas
	| rec |
	scale := 0.006.
	rec := aRSCanvas encompassingRectangle.
	translation := (rec floatCenter negated * scale) + (0@rec height negated * scale).
	aRSCanvas shapes
		do: [ :shape | shape accept: self ]
		separatedBy: [ stream crlf ]
```

**Comment by akevalion** [comment]
Nice!
