### ISSUE TITLE
Check support of Augmented Reality in AFrame

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3Exporters#15]
It would be nice use AR in Aframe, please check this blog
https://aframe.io/blog/arjs/

**Comment by ThisIsAntonio** [comment]
The AR and QR frame are OK and working in the proyect.
you can use "withAR" or "wihtQR"  in the playground.
Now when use QR, you need "QR hiro" print it. (https://stemkoski.github.io/AR-Examples/markers/hiro.png)
You can see working it here "https://youtu.be/s1f6oU--Iig".
and wihtAR working here "https://youtu.be/vxrNSZqtZ7o".

**Comment by akevalion** [comment]
Nice work!
