### ISSUE TITLE
Issue with popup position in AR

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3Exporters#20]
Currently there is a bad position popup in AR version

![image](https://user-images.githubusercontent.com/10532890/100269062-ba940600-2f34-11eb-8da9-856ab232ba85.png)

Ideally the position of this popup should be near the cursor or at top or bottom of the shape

**Comment by ThisIsAntonio** [comment]
I update the popUp position, this now appears below the camera. Add images about this.

![image](https://user-images.githubusercontent.com/51344799/101036040-add96880-3559-11eb-8525-e29f94b1ac73.png)

![image](https://user-images.githubusercontent.com/51344799/101036107-b29e1c80-3559-11eb-8e02-2e4c6f6faeff.png)

**Comment by akevalion** [comment]
Done
