### ISSUE TITLE
SVG Exporter is broken

### ISSUE THREAD

**Issue by badetitou** [ObjectProfile/Roassal3Exporters#26]
Hello, 

I would like to use the SVG exporter, but it looks like it is broken in the CI (and I have a bug in Pharo)
`ERROR: RSSVGExporterTest 13 ran, 9 passed, 0 skipped, 0 expected failures, 4 failures, 0 errors, 0 passed unexpected`

I think it is a problem with API name modification, but I have no knowledge of Roassal.. Can one of you have a look?

**Comment by akevalion** [comment]
Hi, RSSVGExporter is a new class development for a special client, we will fix this issue. Try to use RSSVGCairoExporter

**Comment by badetitou** [comment]
Sounds ok today
