### ISSUE TITLE
PNG and PDF exporters problem with non-ASCII filenames

### ISSUE THREAD

**Issue by JanBliznicenko** [ObjectProfile/Roassal3Exporters#29]
PNG and PDF exporters do not handle non-ASCII filenames very well. A user of OpenPonk reported that in his case the export did not happen at all and in my case (Windows 10) the resulting file name is complete garbage. Probably some encoding issue along the way of ffi calls.

SVG export works well.

The issue is in Roassal2 as well, that's why I know it (OpenPonk uses Roassal2).

How to reproduce:

```
RSCanvas new pngExporter fileName: 'ěščřžýáíéůúňďťĚŠČŘŽÝÁÍÉŮÚŇĎŤ.png'; export.
RSCanvas new pdfExporter fileName: 'ěščřžýáíéůúňďťĚŠČŘŽÝÁÍÉŮÚŇĎŤ.pdf'; export.
```

![obrazek](https://user-images.githubusercontent.com/9571633/200051051-86e59291-5cdb-45d7-9679-4d7dc1aa2566.png)

**Comment by akevalion** [comment]
Thank you I will review it

**Comment by akevalion** [comment]
I have tried on macOs and I did not found an error. I will review it windows

**Comment by JanBliznicenko** [comment]
You are right, it is Windows-only problem. It works on Debian as well.

**Comment by akevalion** [comment]
Hello I have test it on windows, I yes I got the error, at this moment for png or pdf export Roassal uses AthensCairoPDFSurface for pdf and method `writeToPng:` probably the error is present on windows because of the encoding of the name

**Comment by JanBliznicenko** [comment]
The result seems to be when you try to decode UTF-8 decoded string with Windows-1250 decoder (so it puts UTF-8 somewhere where it expects Windows-1250)

**Comment by JanBliznicenko** [comment]
According to this: https://bugs.freedesktop.org/show_bug.cgi?id=103536
it seems cairo lib used to expect native encoding for each platform in version 1.14 (and older), but since 1.15.10, it works with UTF-8 on all platforms, incl. Windows: https://cairographics.org/releases/ChangeLog.cairo-1.15.10 (search for "UTF").
Stable Pharo VM, unfortunately, uses 1.14.12.

**Comment by akevalion** [comment]
Thank you for this information,
Yes I have tried utf8 on windows but the result is the same.

```st
RSPNGExporter >> #exportToFile: file
	| morph |
	morph := self morph.
	self cameraSetter set: [
		| surface |
		surface := AthensCairoSurface extent: morph extent asIntegerPoint.
		surface drawDuring: [ :can | morph fullDrawOnAthensCanvas: can ].
		surface writeToPng: file pathString utf8Encoded.
		surface flush.
		
		"The following may fail when the VM is run in the headless mode"
		[ surface finish ] on: Error do: [ :ex  | "Do nothing" ]. 
		 ]
```

 Maybe this is an issue then for pharo to update the current version of cairo, also @tinchodias, told me that new cairo supports new features.

**Comment by akevalion** [comment]
We have talk with Pablo Tesone and next week we will update cairo version in pharo11

**Comment by akevalion** [comment]
@JanBliznicenko I check it on windows and it is fixed, you can download the new vm and that will include the new version of cairo

**Comment by JanBliznicenko** [comment]
Thank you, @akevalion 
Is it the VM marked as stable (that is downloaded by Pharo Launcher) or does it need to be latest?

**Comment by akevalion** [comment]
In my case remove my last vm and the PharoLauncher downloaded the new vm.

**Comment by JanBliznicenko** [comment]
Indeed, it works now. And not just in Pharo 11, but also 10 and 9, awesome!
