### ISSUE TITLE
Should not depend on OSSubProcess

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3Exporters#3]
Pavel said:
> it is mixed with the video exporter that requires OSSubprocess that does not work well on Windows which is our primary platform. I recommend splitting it.

**Comment by akevalion** [comment]
we have 2 groups:
- **Core** with exporters package, test and examples
-**Video** with core and the video package

**Comment by akevalion** [comment]
I think we can close this issue

**Comment by akevalion** [comment]
done
