### ISSUE TITLE
RSPNGExporter ignores camera settings, but here's a workaround

### ISSUE THREAD

**Issue by dmatveev** [ObjectProfile/Roassal3Exporters#35]
# Package information

* Windows 11
* Pharo 10.0.0
  - Build information: Pharo-10.0.0+build.535.sha.f72dfb7a95cb072d485373b28b33e8c256b9a3f2 (64 Bit)
* Roassal3 64f2c2d5cf5efda9c4dd14dcdc14b5777767cc69
* Roassal3Exporters f2f81e91d3f892c2c6d2837ec097507faa4eb325

# Background

I have some (quite basic) visualizations which I export to reports in various formats. Sometimes `RSCanvas`-es are exported to PNG, sometimes to SVG. This snippet may be used as an example (or more like a reproducer):

```smalltalk
| c p  |
p := RSColorPalette qualitative set312.
c := RSCanvas new.
c addAll: ((1 to: 500) collect: [ :i |
	RSBox new
		model: i;
		color: (p scale: i);
		x: i*10; width: 10; height: 50;
		yourself ]).
c @ RSCanvasController.
```

This is how it looks like in the Inspector:
![image](https://user-images.githubusercontent.com/144187/224514690-5bc0af8b-2c98-445a-921c-fc5f9ed4253d.png)

In fact, it is a thin long line, and in the exported document I only want to display a part of it (e.g., the beginning, zoomed in and trimmed by the limit of 720px). The following camera setter does this for me:

```smalltalk
'From Pharo10.0.0 of 7 November 2022 [Build information: Pharo-10.0.0+build.535.sha.f72dfb7a95cb072d485373b28b33e8c256b9a3f2 (64 Bit)] on 11 March 2023 at 10:44:41.224 pm'!
RSAbstractCamSetter subclass: #SampleExportCameraSetter
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'MyPackage'!

!SampleExportCameraSetter methodsFor: 'hooks' stamp: 'DM 3/11/2023 21:41'!
extent
	^ 720 @ (canvas encompassingRectangle height)! !

!SampleExportCameraSetter methodsFor: 'hooks' stamp: 'DM 3/11/2023 22:34'!
setCamera
	| allCenter |
	allCenter := canvas encompassingRectangle floatCenter.
	canvas camera
		position: (self extent x / 2) @ allCenter y;
		scale: 1.! !
```

# Problem

While it works perfectly with the RSCairoExporter, it seems the default PNG exporter just ignores it. This is how I use it:
```smalltalk
RSPNGExporter new
	canvas: c;
	fileName: 'C:\dmitry\test-orig.png';
	cameraSetter: SampleExportCameraSetter new;
	export.
```
And this is the result - no zoom to the specified position:
![test-orig](https://user-images.githubusercontent.com/144187/224514932-2e257a48-9083-42ef-8eb1-5b76e395d49e.png)

# Workaround

Since for SVG it worked well and the SVG exporter was Cairo based, and Cairo itself can export its surfaces to PNG, I decided to write my own simple Cairo-based PNG exporter. This is what I ended up with (and it works):

```smalltalk
'From Pharo10.0.0 of 7 November 2022 [Build information: Pharo-10.0.0+build.535.sha.f72dfb7a95cb072d485373b28b33e8c256b9a3f2 (64 Bit)] on 11 March 2023 at 10:51:53.106 pm'!
RSCairoExporter subclass: #SamplePNGCairoExporter
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'MyPackage'!

!SamplePNGCairoExporter methodsFor: 'public' stamp: 'DM 3/11/2023 21:38'!
exportToFile: file
	| surface oldSurface morph |
	surface := AthensCairoSurface extent: cameraSetter extent.
	morph := self morph.
	self cameraSetter set: [ 
		oldSurface := morph surface.
		morph surface: surface.
		
		morph drawShapes.
		surface writeToPng: file pathString.
		
		surface := nil.
		morph surface: oldSurface. ].! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

SamplePNGCairoExporter class
	instanceVariableNames: ''!

!SamplePNGCairoExporter class methodsFor: 'accessing' stamp: 'DM 3/11/2023 21:38'!
extension
	^ 'png'! !
```
![test-mine](https://user-images.githubusercontent.com/144187/224515116-9db171ad-9a34-4eee-850d-961c428f2c5c.png)

**Comment by akevalion** [comment]
Hello @dmatveev thank you for your feedback.

In this case the problem is `RSCanvasController`. This class adds some interactions to the canvas, one of them is `RSZoomToFitCanvasInteraction`, when the canvas changes its extent, `zoomToFit` will be apply on the canvas.

You can configure it to disable this option. but I think the best is not include `RSCanvasController`
Please check this example:

```st
| c p  |
p := RSColorPalette qualitative set312.
c := RSCanvas new.
c addAll: ((1 to: 500) collect: [ :i |
	RSBox new
		model: i;
		color: (p scale: i);
		x: i*10; width: 10; height: 50;
		yourself ]).
"c @ RSCanvasController."

"you can change the extent of the canvas and the camera position and its scale"
c extent: 720@ c encompassingRectangle height.
c camera position: c encompassingRectangle floatCenter.

"use this shortcut to create the png exporter"
c pngExporter
	fileName: 'test.png';
	export.
```
![test](https://user-images.githubusercontent.com/10532890/226586287-683fbc22-8cac-4c79-b36e-d61cb782a8f1.png)

**Comment by dmatveev** [comment]
Thanks @akevalion  -- so I don't even need a camera class, it seems. Ok I will try this approach. I just use the same code to render a canvas both for inspector _and_ export, so the `RSCanvasController` gets there by default. Good to know!
