### ISSUE TITLE
Can we have a simple SVG importer?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3Exporters#4]
Pavel said:
> Roassal3 seems to miss now an easy way how to import SVGs (as XML files)

**Comment by akevalion** [comment]
This is a roassal3 issue

**Comment by akevalion** [comment]
Consider
```Smalltalk
c := RSAnimationExamples new example26Bezier.
c svgExporter export.
```
![image](https://user-images.githubusercontent.com/10532890/95375231-b5f88d00-08b5-11eb-8795-7d578b0495b6.png)

Roassal3 has an svg exporter with athens cairo

**Comment by akevalion** [comment]
the SVG Importer is related to roassal3 or maybe an external project.
in Roassal3 you have to use Roassal3-SVG-Importer, package. to download use the script
```st
[Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3';
    load: 'SVGImporter' ] on: MCMergeOrLoadWarning do: [:warning | warning load ]
```
