### ISSUE TITLE
Create a mesh plane

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3Exporters#5]
Because the cylinder is not working with interaction mouse enter, mouse leave

Could you add a default mesh plane to the 3d scene. The popup for aframe-roassal should work for aframe

**Comment by ThisIsAntonio** [comment]
I check the problem and I modify the PopUp, because the problem was in the position, so the problem with the cylinder entity frame are OK.

**Comment by akevalion** [comment]
Is not need it now
