### ISSUE TITLE
create a basic popup text for aframe

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3Exporters#6]
Roassal3D shapes needs to add a basic popup when they have a model.

![image](https://user-images.githubusercontent.com/10532890/95088842-d4b22480-06f9-11eb-8f94-025bba9c875c.png)

**Comment by akevalion** [comment]
@ThisIsAntonio the popup in AFrame should use the current model of each shape as string.

**Comment by ThisIsAntonio** [comment]
The PopUp are Ok and running.
Add Code about this, and images.

```smalltalk
visitCanvas: aRSCanvas 
	stream << '<a-camera position="0 1.6 4">';
		    << '<a-text id="idPopUP" ';
		    << ' align="center" width="2.5" color="#FFF"';
		    << 'visible="false" position="2 2 -4" geometry="primitive: plane; width: 1.75"';
		    << 'material="color: #333"></a-text> ';
		    << '<a-cursor></a-cursor></a-camera>'; crlf.
	aRSCanvas shapes do: [ :shape | shape accept: self ] separatedBy: [ stream crlf ].
```

![image](https://user-images.githubusercontent.com/51344799/97219830-57824880-17a9-11eb-94fe-f19c80bef812.png)

![image](https://user-images.githubusercontent.com/51344799/97219869-6537ce00-17a9-11eb-8437-57ed0b18ecd9.png)

**Comment by akevalion** [comment]
Works well
