### ISSUE TITLE
New Shapes in aFrame Ellipse

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3Exporters#8]
Currently AFrame exporter support Box and Cube

RSEllipse in aFrame should be a Cylinder.

**Comment by akevalion** [comment]
Maybe users in pharo can set the depth with a property in the canvas. 
```Smalltalk
canvas propertyAt: #depth put: 10
```
Then AFrame exporter can use this depth for the export in all shapes.

**Comment by ThisIsAntonio** [comment]
The RSEllipse are running ok, and the lines don't interrump the PopUp.

![image](https://user-images.githubusercontent.com/51344799/97220052-a5974c00-17a9-11eb-8996-42b0e7dd048e.png)

**Comment by akevalion** [comment]
Excellent!
