### ISSUE TITLE
Do not use a base64 image use a link to one image in the web for aframe floor

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3Exporters#9]
Please remove the base64 image in aframe exporter and add the image texture in a server

**Comment by ThisIsAntonio** [comment]
I changed the code in Base64 to JPG archive, and upload in "IMGUR" web page It. Later I changed the code in Roassal3-Exporters-Aframe and Add the direct link to the Image.

**Comment by ThisIsAntonio** [comment]
![CapturaPharo](https://user-images.githubusercontent.com/51344799/96177535-6729a380-0f04-11eb-91c5-8cf5e39c0e6e.PNG)
![CapturaHtml](https://user-images.githubusercontent.com/51344799/96177545-6a249400-0f04-11eb-8f85-ab78db375a4c.PNG)
![CapturaCodigoHtml](https://user-images.githubusercontent.com/51344799/96177567-70b30b80-0f04-11eb-9011-c872ec12ebbe.PNG)

**Comment by akevalion** [comment]
Good!

**Comment by bergel** [comment]
But, do we really need the floor? Is there a way to disable it?

**Comment by ThisIsAntonio** [comment]
the code can disable add example

```smalltalk
	| canvas box |
	canvas := RSCanvas new.
	
	box := RSBox new
		size: 100;
		draggable;
		position: -100@150;
		yourself.
	canvas add: box.
	canvas add: (
		RSLine new
			from: box;
			to: 0@0;
			color: Color red;
			yourself).
	canvas add: (
		RSLine new
			startPoint: 100@100;
			endPoint: 150@150;
			yourself).
	canvas aFrameExporter noFloor exportAndOpen
```

**Comment by ThisIsAntonio** [comment]
![image](https://user-images.githubusercontent.com/51344799/96790497-47472380-13cd-11eb-9e5f-b04858b66a46.png)
